### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor. 

### ISSUE THREAD

**Issue by adamhongmy** [netguru/ResponseDetective#48] opened 2017-10-27 03:01 UTC
I'm using ResponseDetective (1.2.0) in xcode 9.0.1 using Objective C. Xcode even gave me "Use of undeclared identifier 'RDTResponseDetective'".

**Comment by akashivskyy** [comment] 2017-10-27 11:19
Did you try doing what the error suggests to do? :)

**Comment by adamhongmy** [comment] 2017-10-30 04:24
Hi, sorry for late reply. I thought the setting it mentioned is the framework. I will try tomorrow.

**Comment by adamhongmy** [comment] 2017-10-31 10:59
I had configure it and it works. Thanks for your patience. Cheers

**Comment by adamhongmy** [comment] 2018-03-26 03:19
Hello, can you set the swift language version on your end? It is getting tedious to reset it every time.

**Comment by akashivskyy** [comment] 2018-03-26 07:55
Hi @adamhongmy, I'm not sure what you mean. Swift Version build setting _is_ set up here.

**Comment by adamhongmy** [comment] 2018-03-27 02:32
Weird, everytime I run pod install in the terminal, I always get this error in xcode and I have to manually reconfigure it.

**Comment by adamhongmy** [comment] 2018-03-27 04:00
As an alternative, I use Carthage instead. It doesn't seem to be having the error.

**Comment by akashivskyy** [comment] 2018-03-27 06:34
What's your version of CocoaPods?

**Comment by adamhongmy** [comment] 2018-03-28 02:36
Allo, sorry for the delay. My version is 1.3.1

**Comment by akashivskyy** [comment] 2018-03-28 07:41
Okay, last question: is the error thrown for ResponseDetective target in Pods.xcodeproj or for your own app target?

**Comment by adamhongmy** [comment] 2018-03-28 08:13
It is from Pods.xcodeproj. 
<img width="536" alt="screen shot 2018-03-28 at 4 12 16 pm" src="https://user-images.githubusercontent.com/11060748/38016864-f832cc8a-32a2-11e8-8426-3f03fffc1a26.png">

**Comment by akashivskyy** [comment] 2018-04-03 13:49
I can't reproduce this error – I created a brand new project in Xcode 9.2, added ResponseDetective as CocoaPods dependency, installed it and built the project successfully. Please make sure you're not modifying any targets auto-created by CocoaPods and use a compatible version of ResponseDetective.

I'm closing the issue for now. If you still believe that the error lies on the side of ResponseDetective, please open a new issue and provide more information, such as a sample project with failing configuration.

**Closed as completed by akashivskyy** 2018-04-03 13:49 UTC
