### ISSUE TITLE
Crashing on iOS 10.3.1

### ISSUE THREAD

**Issue by SandeepAggarwal** [netguru/ResponseDetective#30] opened 2017-04-20 09:42 UTC
The app is crashing without any message on iOS 10.3.1.
Upon rebuilding the 'ResponseDetective' using `Carthage update --platform ios` it is giving following error:

>  <unknown>:0: warning: argument unused during compilation: '-iapinotes-modules /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/arm64

**Comment by akashivskyy** [comment] 2017-04-23 09:12
Are you sure this isn't your app's fault? 😉 I cannot reproduce this, using an iPhone 7 running iOS 10.3.1 and Xcode 8.3.1 on macOS 10.12.4. 

Also, apps never crash without any message or crash log. Please search for one and provide it so that it is possible to diagnoze the error.

As for the warning – it seems to be an issue with flags passed by Xcode to Swift compiler, which is beyond our control. 🙂

**Comment by akashivskyy** [comment] 2017-04-26 10:18
Hi, @SandeepAggarwal!

Can you confirm that the issue is on ResponseDetective's side and, if yes, provide some more information on how to reproduce the crash?

**Comment by SandeepAggarwal** [comment] 2017-04-26 10:21
yes, the issue was either of Carthage or ResponseDetective.
As I mentioned in the ticket, the crash issue has gone when I updated the Carthage but it also raised the warning which I have mentioned above.

**Comment by SandeepAggarwal** [comment] 2017-04-26 10:26
Prior to update , I had  ResponseDetective  with the commit ID: 'b0276c6' and I have updated it to commit with ID: '1fd7eee'.

Hope this helps to reproduce the issue.

**Comment by akashivskyy** [comment] 2017-04-26 12:10
It is almost impossible for me to reproduce the issue without any hint. :wink: Between b0276c6...1fd7eee there were no changes that could potentially fix a runtime crash (the only thing that was fixed was a compile-time static analyzer error).

If this happens again, please include any logs and other information that may help in locating the issue.

As for the warning during `carthage update`, it is not connected with ResponseDetective – it might be a Carthage issue or potentially incompatible Xcode version.

P.S. I advice locking dependencies to _version_, not specific _commits_.

**Comment by akashivskyy** [comment] 2017-04-26 12:11
As the issue is gone on your side and I cannot reproduce it, I'm closing this issue for the moment. If it ever happens again, feel free to either reopen this one, or create a new one. 🙂

**Closed as completed by akashivskyy** 2017-04-26 12:11 UTC
